language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build -v
  - cargo doc -v
after_success:
  - curl http://docs.piston.rs/travis-doc-upload.sh | sh
